version: "3.5"
services:
  virgolland:
    image: goldenstarc/virgollanding:latest
    restart: unless-stopped
    container_name: virgol_landing
    # build:
    #   context: .
    environment:
      - ASPNETCORE_URLS=http://+ # ;https://+
      - ASPNETCORE_ENVIRONMENT=Production
      - NODE_ENV=production
      - VIRGOL_SERVER_ROOT_URL=https://vir-gol.ir
      - VIRGOL_DATABASE_HOST=postgres.vir-gol.ir
      - VIRGOL_DATABASE_PORT=5432
      - VIRGOL_DATABASE_NAME=VirgolLanding
      - VIRGOL_DATABASE_USER=postgres
      - VIRGOL_DATABASE_PASSWORD=PostgreSQLpass.24
      - VIRGOL_FARAZAPI_URL=http://rest.ippanel.com
      - VIRGOL_FARAZAPI_SENDER_NUMBER=+983000505
      - VIRGOL_FARAZAPI_USERNAME=goldenstarc
      - VIRGOL_FARAZAPI_PASSWORD=hektug-fakbAm-0vypje
      - VIRGOL_FARAZAPI_API_KEY=qcP4IQp3PPRV3ppvkG9ScHJcwvUPL3iOJrV9n7QiqDA=
      - VIRGOL_SMTP_HOST=mail.vir-gol.ir
      - VIRGOL_SMTP_PASS=Mailpass.2476
      - VIRGOL_SMTP_PORT=25
      - VIRGOL_JWT_SECRET=Saleh Secret Key
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.virgolLand.rule=Host(`vir-gol.ir`)"
    - "traefik.http.services.virgolLand.loadbalancer.server.port=80"
    - "traefik.http.routers.virgolLand.entrypoints=websecure"
    - "traefik.http.routers.virgolLand.tls.certresolver=letsencrypt"
    - "traefik.docker.network=traefik-network"
 #     - "traefik.http.middlewares.virgol_compress.compress=true"
 #     - "traefik.http.routers.virgol.middlewares=virgol_compress"
    networks:
      - web
networks:
  web:
    external: true
