http:
  routers:
    ohif:
      rule: "Host(`ohif.c1tech.group`)"
      service: ohif
      entryPoints:
        - websecure
      tls:
        certresolver: letsencrypt
  services:
    ohif:
      loadBalancer:
        servers:
          - url: "http://172.25.10.16:8889"
        passHostHeader: true

