

networks:
  traefik-network:
    external: true

services:
  mirotalk:
    image: mirotalk/p2p:latest
    container_name: mirotalkp2p
    hostname: mirotalkp2p
    volumes:
        - .env:/src/.env:ro
        # Rebranding:
        # - ./app/src/config.js:/src/app/src/config.js:ro
        # Optional volumes for real-time updates:
        # - ./app/:/src/app/:ro
        # - ./public/:/src/public/:ro
    restart: unless-stopped
    # ports:
    #     - '${PORT}:${PORT}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mirotalkp2p.rule=Host(`${MIROTALK_P2P_HOSTNAME}`)"
      - "traefik.http.routers.mirotalkp2p.service=mirotalkp2p"
      - "traefik.http.routers.mirotalkp2p.entrypoints=websecure"
      - "traefik.http.services.mirotalkp2p.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.mirotalkp2p.tls=true"
      - "traefik.http.routers.mirotalkp2p.tls.certresolver=letsencrypt"
      - "traefik.http.services.mirotalkp2p.loadbalancer.passhostheader=true"
      - "traefik.http.routers.mirotalkp2p.middlewares=traefik-compress"
      - "traefik.http.middlewares.traefik-compress.compress=true"
      - "traefik.http.routers.mirotalkp2p.middlewares=authentik@docker"
      - "traefik.docker.network=traefik-network"
    networks:
      - traefik-network
